services:
  db:
    image: mysql:latest
    container_name: parrots_db_container
    env_file: "backend.env"
    # x:y means that x redirects into 3306 which is mysql standard
    ports:
      - "3333:3306"
    volumes:
      - parrots_db_data:/var/lib/mysql
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql

  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: parrots_api_container
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: "backend.env"
    working_dir: /usr/src
    command: ["npm", "run", "start"]

volumes:
  parrots_db_data:
